; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = main

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17
    -D SERIAL_TX_BUFFER_SIZE=256
    -D SERIAL_RX_BUFFER_SIZE=256
	
[env:main]
build_src_filter = +<main.cpp> +<mainmenu.cpp> -<po_*>
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.4
	olikraus/U8g2@^2.36.18
	feilipu/FreeRTOS@^11.1.0-3


[env:poc_screen]
build_src_filter = +<poc_screen.cpp> -<main.cpp> -<mainmenu.cpp>
lib_deps = 
	olikraus/U8g2@^2.36.18
	feilipu/FreeRTOS@^11.1.0-3
